# remote_theme: trylaarsdam/jekyll-theme-console
markdown: kramdown

remote_theme: trylaarsdam/jekyll-theme-console
style: light
header_pages:
  - index.md
  - aboutme.md
  - contact.md
footer: '© 2022 Windy City Lab, LLC -- all rights reserved'
