# remote_theme: trylaarsdam/jekyll-theme-console
markdown: kramdown

plugins:
  - jekyll-redirect-from

remote_theme: trylaarsdam/jekyll-theme-console
style: light
header_pages:
  - index.md
  - ai-capabilities.md
  - aboutme.md
  - contact.md
footer: '© 2025 Windy City Lab, LLC -- all rights reserved'